LABELFONT = ("Roboto", 14)
BUTTONFONT = ("Roboto", 14, "bold")
ENTRYFGCOLOR = "#E0DFDF"
ENTRYBORDERCOLOR = "#c2c0c0"
BUTTONFGCOLOR = "#98a164"
BUTTONHOVERCOLOR = "#5c613e"
BUTTONTEXTCOLOR = "#FFFFFF"
BUTTONBORDERCOLOR = "#585c45"
